#!/bin/bash
#
# get-credentials.sh - Retrieve Cal.com Database Credentials and Connection Information
#
# DESCRIPTION:
#   This script retrieves database credentials from AWS Secrets Manager and
#   connection details from CloudFormation stack outputs. It outputs all the
#   information needed to connect to the Cal.com PostgreSQL database.
#
# PREREQUISITES:
#   - AWS CLI installed and configured with appropriate credentials
#   - jq command-line JSON processor installed
#   - CalComInfrastructureStack must be deployed
#   - IAM permissions for:
#     - secretsmanager:GetSecretValue on calcom-db-credentials
#     - cloudformation:DescribeStacks on CalComInfrastructureStack
#
# USAGE:
#   ./scripts/get-credentials.sh
#   npm run get-credentials
#
# OUTPUT:
#   The script outputs:
#   - Database username and password
#   - Connection endpoint, port, and database name
#   - Ready-to-use PostgreSQL connection string
#   - Export commands for environment variables
#
# EXAMPLE OUTPUT:
#   Database Credentials:
#   ====================
#   Username: calcom_admin
#   Password: <auto-generated-password>
#
#   Connection String:
#   ====================
#   postgresql://calcom_admin:<password>@<endpoint>:5432/calcom
#
# EXIT CODES:
#   0 - Success
#   1 - Failed to retrieve credentials (stack not deployed or missing permissions)
#
# SECURITY NOTE:
#   This script outputs sensitive credentials to stdout. Avoid running in
#   shared environments or logging the output. Consider piping to a secure
#   credential manager or using the output directly in your application.
#

echo "Retrieving Cal.com database credentials..."
echo ""

# Retrieve the database credentials secret from AWS Secrets Manager.
# The secret contains a JSON object with 'username' and 'password' keys.
SECRET=$(aws secretsmanager get-secret-value --secret-id calcom-db-credentials --query SecretString --output text 2>/dev/null)

# Check if the secret retrieval was successful.
# Common failure reasons: stack not deployed, missing IAM permissions, wrong region.
if [ $? -ne 0 ]; then
  echo "Error: Could not retrieve credentials. Make sure the stack is deployed and you have AWS credentials configured."
  exit 1
fi

# Parse the JSON secret to extract username and password using jq.
USERNAME=$(echo $SECRET | jq -r '.username')
PASSWORD=$(echo $SECRET | jq -r '.password')

# Retrieve connection details from CloudFormation stack outputs.
# These outputs are defined in lib/cal.com-infrastructure-stack.ts.
ENDPOINT=$(aws cloudformation describe-stacks --stack-name CalComInfrastructureStack --query 'Stacks[0].Outputs[?OutputKey==`DBEndpoint`].OutputValue' --output text 2>/dev/null)
PORT=$(aws cloudformation describe-stacks --stack-name CalComInfrastructureStack --query 'Stacks[0].Outputs[?OutputKey==`DBPort`].OutputValue' --output text 2>/dev/null)
DBNAME=$(aws cloudformation describe-stacks --stack-name CalComInfrastructureStack --query 'Stacks[0].Outputs[?OutputKey==`DBName`].OutputValue' --output text 2>/dev/null)

# Output the retrieved credentials and connection information.
echo "Database Credentials:"
echo "===================="
echo "Username: $USERNAME"
echo "Password: $PASSWORD"
echo ""
echo "Connection Details:"
echo "===================="
echo "Endpoint: $ENDPOINT"
echo "Port: $PORT"
echo "Database: $DBNAME"
echo ""

# Output a ready-to-use PostgreSQL connection string.
# This format is compatible with most PostgreSQL clients and ORMs.
echo "Connection String:"
echo "===================="
echo "postgresql://$USERNAME:$PASSWORD@$ENDPOINT:$PORT/$DBNAME"
echo ""

# Output export commands for setting environment variables.
# Copy and paste these into your shell or add to your .env file.
echo "Environment Variables:"
echo "===================="
echo "export DATABASE_URL=\"postgresql://$USERNAME:$PASSWORD@$ENDPOINT:$PORT/$DBNAME\""
echo "export DB_HOST=\"$ENDPOINT\""
echo "export DB_PORT=\"$PORT\""
echo "export DB_NAME=\"$DBNAME\""
echo "export DB_USER=\"$USERNAME\""
echo "export DB_PASSWORD=\"$PASSWORD\""
